# Ansible playbook for shuttown down the honeynet traffic capture scripts
---

- name: Stop management program on backend
  hosts: backend
  connection: local
  tasks:
          - name: Kill management script
            ansible.builtin.shell: "kill -9 $(ps aux | grep \"manage_captures\" | head -n 1 | awk '{print $2}') &> /dev/null"
          - name: Kill logmon script
            ansible.builtin.shell: "kill -9 $(ps aux | grep \"log_mon\" | head -n 1 | awk '{print $2}') &> /dev/null"

- name: Stop management program on remote Linux hosts
  hosts: webserver, ftp_server, database
  remote_user: ansible
  become: yes
  tasks:
        # Run the script on the boxes
          - name: Kill capture script
            ansible.builtin.shell: "kill -9 $(ps aux | grep \"manage_captures\" | head -n 1 | awk '{print $2}') &> /dev/null"


- name: Stop management program on remote Windows hosts
  hosts: windows10
  remote_user: ansible
  tasks:
        # Run the script on the boxes
          - name: Kill capture script
            ansible.windows.win_powershell:
                # import the process handle from the XML saved location
                script: |
                  $proc = Import-Clixml -Path C:\Users\ansible\caps\manage_captures_process_handle.xml
                  $proc | Stop-Process
